apiVersion: v1
kind: Secret
metadata:
   name: nabhi-env
   annotations:
   description: Configuracion de URLS y DataSource para Nabhi
stringData:
    OPENSHIFT_NABHI_ATM_JDB_DB_USERNAME: "ATM2"
    OPENSHIFT_NABHI_ATM_JDB_DB_PASSWORD: "ATM2"
    OPENSHIFT_NABHI_ATM_JDB_DB_HOST: "172.16.136.135"
    OPENSHIFT_NABHI_ATM_JDB_DB_PORT: "1533"
    OPENSHIFT_NABHI_ATM_JDB_DB_INSTANCE: "RED"
    OPENSHIFT_NABHI_ATM_JDB_DATASOURCE: "java:jboss/datasources/atmcloud"
    OPENSHIFT_NABHI_ATM_JDB_POOLNAME: "CAN-POOL"
    OPENSHIFT_NABHI_PRIKEY: "Vz2X4XcNUd2JXG5K"
    OPENSHIFT_NABHI_ATM_LDAP_PRINCIPAL: "cn=IdentitySSO,ou=People,o=isp"
    OPENSHIFT_NABHI_ATM_LDAP_PASSWORD: "Id3nt1tyss0"
    OPENSHIFT_NABHI_ATM_KS_LOCATION: "/home/keystore/nabhi.jks"
    OPENSHIFT_NABHI_ATM_KS_PASSWORD: "3AED23CFFFDE2312"
    #Cambio release/redcat
    OPENSHIFT_NABHI_ATM_FTP_USER: "user"
    OPENSHIFT_NABHI_ATM_FTP_PASSWORD: "password"
    #Cambio release/redcat