package mx.com.prosa.nabhi.misc.model.esq;

import mx.com.prosa.nabhi.misc.exception.CatalogError;
import mx.com.prosa.nabhi.misc.exception.XFSException;

public enum XFSToDDC {

    XFS_1( -200, "WFS_ERR_IDC_MEDIAJAM", 10, "TERMINAL \\S CARD READER ERROR", -2, 2 ),
    XFS_2( -201, "WFS_ERR_IDC_NOMEDIA", 10, "TERMINAL \\S CARD READER ERROR", -1, 2 ),
    XFS_3( -202, "WFS_ERR_IDC_MEDIARETAINED", 10, "TERMINAL \\S CARD READER ERROR", -1, 2 ),
    XFS_4( -203, "WFS_ERR_IDC_RETAINBINFULL", 10, "TERMINAL \\S CARD READER ERROR", -2, 2 ),
    XFS_5( -204, "WFS_ERR_IDC_INVALIDDATA", 901, "ATM \\S, READ INTERNAL ERROR", 0, 2 ),
    XFS_6( -205, "WFS_ERR_IDC_INVALIDMEDIA", 307, "BAD CARD TRACK 2", 0, 2 ),
    XFS_7( -206, "WFS_ERR_IDC_FORMNOTFOUND", 307, "BAD CARD TRACK 2", -1, 2 ),
    XFS_8( -207, "WFS_ERR_IDC_FORMINVALID", 307, "BAD CARD TRACK 2", -1, 2 ),
    XFS_9( -208, "WFS_ERR_IDC_DATASYNTAX", 307, "BAD CARD TRACK 2", -1, 2 ),
    XFS_10( -209, "WFS_ERR_IDC_SHUTTERFAIL", 662, "THE OPEN OF THE SECURITY MODULE FAILED", -2, 2 ),
    XFS_11( -210, "WFS_ERR_IDC_SECURITYFAIL", 663, "THE SECURITY MODULE HAS FAILED", -2, 2 ),
    XFS_12( -211, "WFS_ERR_IDC_PROTOCOLNOTSUPP", 10, "TERMINAL \\S CARD READER ERROR", -1, 2 ),
    XFS_13( -212, "WFS_ERR_IDC_ATRNOTOBTAINED", 307, "BAD CARD TRACK 2", -1, 2 ),
    XFS_14( -213, "WFS_ERR_IDC_INVALIDKEY", 711, "LOADKEY OPTION NOT SUPPORTED", -1, 2 ),
    XFS_15( -214, "WFS_ERR_IDC_WRITE_METHOD", 449, "ATM \\S, WRITE INTERNAL ERROR", -1, 2 ),
    XFS_16( -215, "WFS_ERR_IDC_CHIPPOWERNOTSUPP", 700, "INVALID COMMAND", -1, 2 ),
    XFS_17( -216, "WFS_ERR_IDC_CARDTOOSHORT", 306, "BAD CARD ACCT NO", -1, 2 ),
    XFS_18( -217, "WFS_ERR_IDC_CARDTOOLONG", 306, "BAD CARD ACCT NO", -1, 2 ),
    XFS_19( -218, "WFS_ERR_IDC_INVALID_PORT", 10, "TERMINAL \\S CARD READER ERROR", -1, 2 ),
    XFS_20( -219, "WFS_ERR_IDC_POWERSAVETOOSHORT", 10, "TERMINAL \\S CARD READER ERROR", -1, 2 ),
    XFS_21( -220, "WFS_ERR_IDC_POWERSAVEMEDIAPRESENT", 10, "TERMINAL \\S CARD READER ERROR", -1, 2 ),
    XFS_22( -221, "WFS_ERR_IDC_CARDPRESENT", 10, "TERMINAL \\S CARD READER ERROR", -1, 2 ),
    XFS_23( -222, "WFS_ERR_IDC_POSITIONINVALID", 540, "TERMINAL \\S - SENT A REJECT, ID \\, SUBID \\\\, REASON \\\\", -1, 2 ),
    XFS_24( -223, "WFS_ERR_IDC_INVALIDTERMINALDATA", 669, "INVALID STATEMENT INFORMATION RECEIVED BY", -1, 2 ),
    XFS_25( -224, "WFS_ERR_IDC_INVALIDAIDDATA", 669, "INVALID STATEMENT INFORMATION RECEIVED BY", -1, 2 ),
    XFS_26( -225, "WFS_ERR_IDC_INVALIDKEYDATA", 711, "LOADKEY OPTION NOT SUPPORTED", -1, 2 ),
    XFS_27( -226, "WFS_ERR_IDC_READERNOTCONFIGURED", 10, "TERMINAL \\S CARD READER ERROR", -2, 2 ),
    XFS_28( -227, "WFS_ERR_IDC_TRANSACTIONNOTINITIATED", 700, "INVALID COMMAND", -1, 2 ),
    XFS_29( -228, "WFS_ERR_IDC_COMMANDUNSUPP", 700, "INVALID COMMAND", -1, 2 ),
    XFS_30( -229, "WFS_ERR_IDC_SYNCHRONIZEUNSUPP", 10, "TERMINAL \\S CARD READER ERROR", -1, 2 ),
    XFS_31( -400, "WFS_ERR_PIN_KEYNOTFOUND", 711, "LOADKEY OPTION NOT SUPPORTED", -1, 4 ),
    XFS_32( -401, "WFS_ERR_PIN_MODENOTSUPPORTED", 4, "TERMINAL \\S PIN PAD ERROR", -1, 4 ),
    XFS_33( -402, "WFS_ERR_PIN_ACCESSDENIED", 268, "INVALID ATD.PIN-ENCR-TYPE \\\\ FOR ATM \\S", -1, 4 ),
    XFS_34( -403, "WFS_ERR_PIN_INVALIDID", 318, "TERMINAL \\S - INVALID DEVICE ID RECEIVED", -1, 4 ),
    XFS_35( -404, "WFS_ERR_PIN_DUPLICATEKEY", 4, "TERMINAL \\S PIN PAD ERROR", -1, 4 ),
    XFS_36( -406, "WFS_ERR_PIN_KEYNOVALUE", 711, "LOADKEY OPTION NOT SUPPORTED", -1, 4 ),
    XFS_37( -407, "WFS_ERR_PIN_USEVIOLATION", 4, "TERMINAL \\S PIN PAD ERROR", -1, 4 ),
    XFS_38( -408, "WFS_ERR_PIN_NOPIN", 268, "INVALID ATD.PIN-ENCR-TYPE \\\\ FOR ATM \\S", -1, 4 ),
    XFS_39( -409, "WFS_ERR_PIN_INVALIDKEYLENGTH", 268, "INVALID ATD.PIN-ENCR-TYPE \\\\ FOR ATM \\S", -1, 4 ),
    XFS_40( -410, "WFS_ERR_PIN_KEYINVALID", 4, "TERMINAL \\S PIN PAD ERROR", -1, 4 ),
    XFS_41( -411, "WFS_ERR_PIN_KEYNOTSUPPORTED", 4, "TERMINAL \\S PIN PAD ERROR", -1, 4 ),
    XFS_42( -412, "WFS_ERR_PIN_NOACTIVEKEYS", 4, "TERMINAL \\S PIN PAD ERROR", -1, 4 ),
    XFS_43( -414, "WFS_ERR_PIN_NOTERMINATEKEYS", 4, "TERMINAL \\S PIN PAD ERROR", -1, 4 ),
    XFS_44( -415, "WFS_ERR_PIN_MINIMUMLENGTH", 4, "TERMINAL \\S PIN PAD ERROR", -1, 4 ),
    XFS_45( -416, "WFS_ERR_PIN_PROTOCOLNOTSUPP", 700, "INVALID COMMAND", -1, 4 ),
    XFS_46( -417, "WFS_ERR_PIN_INVALIDDATA", 4, "TERMINAL \\S PIN PAD ERROR", -1, 4 ),
    XFS_47( -418, "WFS_ERR_PIN_NOTALLOWED", 4, "TERMINAL \\S PIN PAD ERROR", -1, 4 ),
    XFS_48( -419, "WFS_ERR_PIN_NOKEYRAM", 4, "TERMINAL \\S PIN PAD ERROR", -1, 4 ),
    XFS_49( -420, "WFS_ERR_PIN_NOCHIPTRANSACTIVE", 4, "TERMINAL \\S PIN PAD ERROR", -1, 4 ),
    XFS_50( -421, "WFS_ERR_PIN_ALGORITHMNOTSUPP", 711, "LOADKEY OPTION NOT SUPPORTED", -1, 4 ),
    XFS_51( -422, "WFS_ERR_PIN_FORMATNOTSUPP", 4, "TERMINAL \\S PIN PAD ERROR", -1, 4 ),
    XFS_52( -423, "WFS_ERR_PIN_HSMSTATEINVALID", 663, "THE SECURITY MODULE HAS FAILED", -1, 4 ),
    XFS_53( -424, "WFS_ERR_PIN_MACINVALID", 510, "TERMINAL \\S INDICATES A ** MAC ** FAILURE.", -1, 4 ),
    XFS_54( -425, "WFS_ERR_PIN_PROTINVALID", 700, "INVALID COMMAND", -1, 4 ),
    XFS_55( -426, "WFS_ERR_PIN_FORMATINVALID", 285, "ATM \\S - INVALID DATA \\ FOUND IN ENHANCED SUPPLY COUNTS MESSAGE. ATD BNA COUNTERS WILL BE SET TO 0.", -1, 4 ),
    XFS_56( -427, "WFS_ERR_PIN_CONTENTINVALID", 663, "THE SECURITY MODULE HAS FAILED", -1, 4 ),
    XFS_57( -429, "WFS_ERR_PIN_SIG_NOT_SUPP", 700, "INVALID COMMAND", -1, 4 ),
    XFS_58( -431, "WFS_ERR_PIN_INVALID_MOD_LEN", 686, "ATM \\S - The ATDD1 record for this terminal contains an invalid ,offset/length pair. Delete and readd the ATD record.", -1, 4 ),
    XFS_59( -432, "WFS_ERR_PIN_INVALIDCERTSTATE", 4, "TERMINAL \\S PIN PAD ERROR", -1, 4 ),
    XFS_60( -433, "WFS_ERR_PIN_KEY_GENERATION_ERROR", 711, "LOADKEY OPTION NOT SUPPORTED", -1, 4 ),
    XFS_61( -434, "WFS_ERR_PIN_EMV_VERIFY_FAILED", 711, "LOADKEY OPTION NOT SUPPORTED", -1, 4 ),
    XFS_62( -435, "WFS_ERR_PIN_RANDOMINVALID", 4, "TERMINAL \\S PIN PAD ERROR", -1, 4 ),
    XFS_63( -436, "WFS_ERR_PIN_SIGNATUREINVALID", 4, "TERMINAL \\S PIN PAD ERROR", -1, 4 ),
    XFS_64( -437, "WFS_ERR_PIN_SNSCDINVALID", 4, "TERMINAL \\S PIN PAD ERROR", -1, 4 ),
    XFS_65( -438, "WFS_ERR_PIN_NORSAKEYPAIR", 4, "TERMINAL \\S PIN PAD ERROR", -1, 4 ),
    XFS_66( -439, "WFS_ERR_PIN_INVALID_PORT", 4, "TERMINAL \\S PIN PAD ERROR", -1, 4 ),
    XFS_67( -440, "WFS_ERR_PIN_POWERSAVETOOSHORT", 4, "TERMINAL \\S PIN PAD ERROR", -1, 4 ),
    XFS_68( -100, "WFS_ERR_PTR_FORMNOTFOUND", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_69( -101, "WFS_ERR_PTR_FIELDNOTFOUND", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_70( -102, "WFS_ERR_PTR_NOMEDIAPRESENT", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_71( -103, "WFS_ERR_PTR_READNOTSUPPORTED", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_72( -104, "WFS_ERR_PTR_FLUSHFAIL", 435, "ERROR WHILE ATTEMPTING TO DELETE TOKEN \\\\ FROM THE ATD - TRAN", -1, 1 ),
    XFS_73( -105, "WFS_ERR_PTR_MEDIAOVERFcash", 424, "MAXIMUM PRINTER DATA REACHED FOR ATM \\S, RECEIPT GROUP \\\\\\\\, TRAN CODE \\\\ - INCR ATD LINES/RCPT OR REDUCE DATA IN RCPT RECORD", -1, 1 ),
    XFS_74( -106, "WFS_ERR_PTR_FIELDSPECFAILURE", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_75( -107, "WFS_ERR_PTR_FIELDERROR", 280, "CPLF PRINT FUNCTION ABORTED", -1, 1 ),
    XFS_76( -108, "WFS_ERR_PTR_MEDIANOTFOUND", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_77( -109, "WFS_ERR_PTR_EXTENTNOTSUPPORTED", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_78( -110, "WFS_ERR_PTR_MEDIAINVALID", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_79( -111, "WFS_ERR_PTR_FORMINVALID", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_80( -112, "WFS_ERR_PTR_FIELDINVALID", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_81( -113, "WFS_ERR_PTR_MEDIASKEWED", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_82( -114, "WFS_ERR_PTR_RETRACTBINFULL", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_83( -115, "WFS_ERR_PTR_STACKERFULL", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_84( -116, "WFS_ERR_PTR_PAGETURNFAIL", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_85( -117, "WFS_ERR_PTR_MEDIATURNFAIL", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_86( -118, "WFS_ERR_PTR_SHUTTERFAIL", 272, "OPEN ERROR ON \\F, ERROR \\E", -1, 1 ),
    XFS_87( -119, "WFS_ERR_PTR_MEDIAJAMMED", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -2, 1 ),
    XFS_88( -120, "WFS_ERR_PTR_FILE_IO_ERROR", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_89( -121, "WFS_ERR_PTR_CHARSETDATA", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_90( -122, "WFS_ERR_PTR_PAPERJAMMED", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -2, 1 ),
    XFS_91( -123, "WFS_ERR_PTR_PAPEROUT", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -2, 1 ),
    XFS_92( -124, "WFS_ERR_PTR_INKOUT", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -2, 1 ),
    XFS_93( -125, "WFS_ERR_PTR_TONEROUT", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -2, 1 ),
    XFS_94( -126, "WFS_ERR_PTR_LAMPINOP", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_95( -127, "WFS_ERR_PTR_SOURCEINVALID", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_96( -128, "WFS_ERR_PTR_SEQUENCEINVALID", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_97( -129, "WFS_ERR_PTR_MEDIASIZE", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -2, 1 ),
    XFS_98( -130, "WFS_ERR_PTR_INVALID_PORT", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_99( -131, "WFS_ERR_PTR_MEDIARETAINED", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_100( -132, "WFS_ERR_PTR_BLACKMARK", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_101( -133, "WFS_ERR_PTR_DEFINITIONEXISTS", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_102( -134, "WFS_ERR_PTR_MEDIAREJECTED", 316, "TERMINAL \\S - INVALID RECEIPT OPTION SET ON ATD FOR STATEMENT. PRINT.  RECEIPT PRINTER MUST BE USED", -1, 1 ),
    XFS_103( -135, "WFS_ERR_PTR_MEDIARETRACTED", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_104( -136, "WFS_ERR_PTR_MSFERROR", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_105( -137, "WFS_ERR_PTR_NOMSF", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_106( -138, "WFS_ERR_PTR_FILENOTFOUND", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_107( -139, "WFS_ERR_PTR_POWERSAVETOOSHORT", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_108( -140, "WFS_ERR_PTR_POWERSAVEMEDIAPRESENT", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_109( -141, "WFS_ERR_PTR_PASSBOOKCLOSED", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -2, 1 ),
    XFS_110( -142, "WFS_ERR_PTR_LASTORFIRSTPAGEREACHED", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -2, 1 ),
    XFS_111( -143, "WFS_ERR_PTR_COMMANDUNSUPP", 700, "INVALID COMMAND", -1, 1 ),
    XFS_112( -144, "WFS_ERR_PTR_SYNCHRONIZEUNSUPP", 3, "TERMINAL \\S STATEMENT PRINTER ERROR,", -1, 1 ),
    XFS_113( -300, "WFS_ERR_CDM_INVALIDCURRENCY", 299, "ATM \\S - NO CURRENCY ACCEPTOR DATA WAS FOUND IN THE ENHANCED. SUPPLY COUNTS MESSAGE. MESSAGE IGNORED.", -1, 3 ),
    XFS_114( -301, "WFS_ERR_CDM_INVALIDTELLERID", 318, "TERMINAL \\S - INVALID DEVICE ID RECEIVED", -1, 3 ),
    XFS_115( -302, "WFS_ERR_CDM_CASHUNITERROR", 7, "TERMINAL \\S ENVELOPE DISPENSER ERROR,", -1, 3 ),
    XFS_116( -303, "WFS_ERR_CDM_INVALIDDENOMINATION", 319, "TERMINAL \\S - INVALID DENOMINATION ID RECEIVED", -1, 3 ),
    XFS_117( -304, "WFS_ERR_CDM_INVALIDMIXNUMBER", 700, "INVALID COMMAND", -1, 3 ),
    XFS_118( -305, "WFS_ERR_CDM_NOCURRENCYMIX", 7, "TERMINAL \\S ENVELOPE DISPENSER ERROR,", -1, 3 ),
    XFS_119( -306, "WFS_ERR_CDM_NOTDISPENSABLE", 281, "DISPENSE ERROR FOR AMT \\\\\\\\\\\\\\\\\\\\\\\\\\\\ - REVIEW ATD", -1, 3 ),
    XFS_120( -307, "WFS_ERR_CDM_TOOMANYITEMS", 281, "DISPENSE ERROR FOR AMT \\\\\\\\\\\\\\\\\\\\\\\\\\\\ - REVIEW ATD", -1, 3 ),
    XFS_121( -308, "WFS_ERR_CDM_UNSUPPOSITION", 7, "TERMINAL \\S ENVELOPE DISPENSER ERROR,", -1, 3 ),
    XFS_122( -310, "WFS_ERR_CDM_SAFEDOOROPEN", 598, "STATE OF ATM \\S HAS CHANGED TO OPEN, BUT ATM IS FAULTED", -2, 3 ),
    XFS_123( -312, "WFS_ERR_CDM_SHUTTERNOTOPEN", 272, "OPEN ERROR ON \\F, ERROR \\E", -2, 3 ),
    XFS_124( -313, "WFS_ERR_CDM_SHUTTEROPEN", 598, "STATE OF ATM \\S HAS CHANGED TO OPEN, BUT ATM IS FAULTED", -2, 3 ),
    XFS_125( -314, "WFS_ERR_CDM_SHUTTERCLOSED", 522, "STATE OF ATM \\S HAS CHANGED TO CLOSED", -2, 3 ),
    XFS_126( -315, "WFS_ERR_CDM_INVALIDCASHUNIT", 7, "TERMINAL \\S ENVELOPE DISPENSER ERROR,", -1, 3 ),
    XFS_127( -316, "WFS_ERR_CDM_NOITEMS", 7, "TERMINAL \\S ENVELOPE DISPENSER ERROR,", -1, 3 ),
    XFS_128( -317, "WFS_ERR_CDM_EXCHANGEACTIVE", 700, "INVALID COMMAND", -1, 3 ),
    XFS_129( -318, "WFS_ERR_CDM_NOEXCHANGEACTIVE", 700, "INVALID COMMAND", -1, 3 ),
    XFS_130( -319, "WFS_ERR_CDM_SHUTTERNOTCLOSED", 7, "TERMINAL \\S ENVELOPE DISPENSER ERROR,", -2, 3 ),
    XFS_131( -320, "WFS_ERR_CDM_PRERRORNOITEMS", 7, "TERMINAL \\S ENVELOPE DISPENSER ERROR,", -1, 3 ),
    XFS_132( -321, "WFS_ERR_CDM_PRERRORITEMS", 7, "TERMINAL \\S ENVELOPE DISPENSER ERROR,", -1, 3 ),
    XFS_133( -322, "WFS_ERR_CDM_PRERRORUNKNOWN", 7, "TERMINAL \\S ENVELOPE DISPENSER ERROR,", -2, 3 ),
    XFS_134( -323, "WFS_ERR_CDM_ITEMSTAKEN", 508, "TERMINAL \\S - CUSTOMER HAD ACCESS TO THE CASH OR NO STACK TO PRESENT", 0, 3 ),
    XFS_135( -327, "WFS_ERR_CDM_INVALIDMIXTABLE", 7, "TERMINAL \\S ENVELOPE DISPENSER ERROR,", -1, 3 ),
    XFS_136( -328, "WFS_ERR_CDM_OUTPUTPOS_NOT_EMPTY", 7, "TERMINAL \\S ENVELOPE DISPENSER ERROR,", 0, 3 ),
    XFS_137( -329, "WFS_ERR_CDM_INVALIDRETRACTPOSITION", 7, "TERMINAL \\S ENVELOPE DISPENSER ERROR,", -1, 3 ),
    XFS_138( -330, "WFS_ERR_CDM_NOTRETRACTAREA", 7, "TERMINAL \\S ENVELOPE DISPENSER ERROR,", -1, 3 ),
    XFS_139( -333, "WFS_ERR_CDM_NOCASHBOXPRESENT", 581, "TERMINAL \\S - CASSETTE # LOW OR OUT OF CASH", -1, 3 ),
    XFS_140( -334, "WFS_ERR_CDM_AMOUNTNOTINMIXTABLE", 299, "ATM \\S - NO CURRENCY ACCEPTOR DATA WAS FOUND IN THE ENHANCED SUPPLY COUNTS MESSAGE. MESSAGE IGNORED.", -1, 3 ),
    XFS_141( -335, "WFS_ERR_CDM_ITEMSNOTTAKEN", 402, "COMPLETION FROM TERMINAL \\S TIMED OUT", -1, 3 ),
    XFS_142( -336, "WFS_ERR_CDM_ITEMSLEFT", 7, "TERMINAL \\S ENVELOPE DISPENSER ERROR,", -2, 3 ),
    XFS_143( -337, "WFS_ERR_CDM_INVALID_PORT", 7, "TERMINAL \\S ENVELOPE DISPENSER ERROR,", -1, 3 ),
    XFS_144( -338, "WFS_ERR_CDM_POWERSAVETOOSHORT", 7, "TERMINAL \\S ENVELOPE DISPENSER ERROR,", -1, 3 ),
    XFS_145( -339, "WFS_ERR_CDM_POWERSAVEMEDIAPRESENT", 7, "TERMINAL \\S ENVELOPE DISPENSER ERROR,", -1, 3 ),
    XFS_146( -340, "WFS_ERR_CDM_POSITION_NOT_EMPTY", 7, "TERMINAL \\S ENVELOPE DISPENSER ERROR,", -2, 3 ),
    XFS_147( -341, "WFS_ERR_CDM_INCOMPLETERETRACT", 7, "TERMINAL \\S ENVELOPE DISPENSER ERROR,", -2, 3 ),
    XFS_148( -342, "WFS_ERR_CDM_COMMANDUNSUPP", 700, "INVALID COMMAND", -1, 3 ),
    XFS_149( -343, "WFS_ERR_CDM_SYNCHRONIZEUNSUPP", 7, "TERMINAL \\S ENVELOPE DISPENSER ERROR,", -1, 3 ),
    XFS_150( -802, "WFS_ERR_SIU_SYNTAX", 700, "INVALID COMMAND", -1, 8 ),
    XFS_151( -803, "WFS_ERR_SIU_PORT_ERROR", 700, "INVALID COMMAND", -2, 8 ),
    XFS_152( -805, "WFS_ERR_SIU_COMMANDUNSUPP", 700, "INVALID COMMAND", -1, 8 );


    XFSToDDC( int xfsCode, String xfsDescription, int ddcCode, String ddcDescription, int severity, int module ) {
        this.xfsCode = xfsCode;
        this.xfsDescription = xfsDescription;
        this.ddcCode = ddcCode;
        this.ddcDescription = ddcDescription;
        this.severity = severity;
        this.module = module;
    }

    private final int xfsCode;
    private final String xfsDescription;
    private final int ddcCode;
    private final String ddcDescription;
    private final int severity;
    private final int module;


    public int getXfsCode() {
        return xfsCode;
    }

    public static XFSEntity searchByXFSCode( final int xfsCode ) throws XFSException {
        for ( XFSToDDC code : XFSToDDC.values() ) {
            if ( xfsCode == code.xfsCode ) {
                return new XFSEntity( code.xfsCode, code.xfsDescription, code.ddcCode, code.ddcDescription, code.severity, code.module );
            }
        }
        throw new XFSException( CatalogError.XFS_NOT_FOUND );
    }


}
