package mx.com.prosa.nabhi.misc.exception;

public enum CatalogError implements ErrorCode {

    NO_ERROR( 0, "Operación correcta ENUM de control", false ),
    SOCKET_ALREADY_ON( 1, "El socket TCP ya se encuentra encendido y conectado", false ),
    SOCKET_ERROR_ON( 2, "Ocurrió un error al iniciar el socket TCP", true ),
    SOCKET_NO_EXIST( 3, "El socket TCP no existe", false ),
    SOCKET_ALREADY_OFF( 4, "El socket TCP ya se encuentra apagado", false ),
    SOCKET_ERROR_OFF( 5, "Ocurrió un error al apagar el socket TCP", true ),
    SOCKET_LIST_EMPTY( 6, "Lista de Sockets TPC vacía", false ),
    SOCKET_NO_EXIST_DB( 7, "El socket TCP no existe en la base de datos", false ),
    SOCKET_ALREADY_EXIST( 8, "El socket TCP ya existe", false ),
    SOCKET_NOT_ON( 9, "El socket TCP no está iniciado", false ),
    SOCKET_NOT_CONTROLLER( 10, "El socket TCP no tiene un controlador TCP configurado", true ),
    SOCKET_NOT_LOGON( 11, "No existe un logon con Base 24", false ),
    SOCKET_ALREADY_LOGON( 12, "Ya existe un logon con Base 24", false ),
    ECHO_ALREADY_EXIST( 13, "Ya existe un echo para este socket TCP", false ),
    INVALID_PATH_VARIABLE( 14, "Variable tipo Path invalida", true ),
    INVALID_URL( 15, "URL invalida", true ),
    INVALID_PARAM( 16, "El parámetro es requerido", false ),
    INVALID_CLASS( 17, "La clase definida es invalida", false ),
    HTTP_CLIENT_ERROR( 18, "Ocurrió un error en la petición", false ),
    HTTP_SERVER_ERROR( 19, "Ocurrió un error de lado del servidor", false ),
    HTTP_SERVER_ERROR_2( 20, "Respuesta invalida del servidor", false ),
    RAML_DEFINITION_ERROR( 21, "La definición del archivo RAML es incorrecta", false ),
    AUTHORIZATION_ERROR( 22, "Hubo un error en la solicitud de autorización", false ),
    CONTEXT_ERROR( 23, "El atributo contexto del objeto es nulo", false ),
    CONTEXT_SERVER_ERROR( 24, "El atributo server es null", false ),
    CONTEXT_AUTH_ERROR( 25, "Se requiere indicar la clase para la autorización", false ),
    CONTEXT_REFLECTION_ERROR( 26, "Hubo un error en la reflexión de la fabrica", false ),
    CONTEXT_URL_ERROR( 27, "La URL del servidor en nula", false ),
    CONTEXT_METHOD_ERROR( 28, "El método HTTP es nulo", false ),
    RESOURCE_ACCESS( 29, "No se pudo realizar la petición debido a que la URL del servicio es incorrecta o no está desplegado el servicio", false ),
    TIME_OUT( 30, "Tiempo excedido de respuesta por parte de Base 24", false ),
    DEVICE_ERROR( 31, "Ocurrió un error entre Base 24 y el HSM", false ),
    IPK_ERROR( 32, "Ocurrió un problema con la llave IPK", false ),
    DATA_ERROR( 33, "Alguno de los parámetros recibidos es invalido", false ),
    DATA_ERROR_2( 34, "Alguno de los parámetros enviados es invalido", false ),
    SANITIZE_ERROR( 35, "Error con la llave IPK y el PIN BLOCK", false ),
    DATABASE_ERROR( 36, "Error en el ATD o el HSM", false ),
    UNKNOWN_ERROR( 37, "Ocurrió un error inesperado en Base 24", false ),
    SANITIZE_INPUT_ERROR( 38, "JSON de entrada corrupto o invalido", false ),
    INVALID_TRANSACTION( 39, "El código de transacción es invalido o no está soportado", false ),
    ISSUER_INOPERATIVE_TIMEOUT( 40, "La respuesta de Base 24 no llego y expiro el tiempo de espera", false ),
    SYSTEM_ERROR( 41, "Ocurrió un error en el Sistema", false ),
    NIP_INVALID( 42, "Cambio de NIP Invalido", false ),
    JKE_ERROR( 43, "Ocurrió un error durante el traslado de PIN BLOCK", false ),
    TOKEN_BUILD_ERROR( 44, "Error al construir el Token", false ),
    TOKEN_ID_NO_EXIST( 45, "El token no es soportado", false ),
    THREAD_ERROR( 46, "Error en los hilos del servicio", true ),
    TCP_NO_READY( 47, "La conexión TCP no está lista para enviar el mensaje", false ),
    ATM_NOT_ONLINE( 48, "El cajero no está en línea", false ),
    ATM_NOT_EXIST( 49, "El cajero no existe", false ),
    ATM_NOT_ALLOW( 50, "El cajero no está autorizado. Se intenta firmar un cajero que no está dado de alta", false ),
    ATM_NOT_GENERATE_TOKEN( 51, "Error al generar el Web Token para el cajero", false ),
    FILE_NO_STORAGE( 52, "No se puede construir el servicio de almacenamiento", false ),
    FILE_NO_PATH( 53, "El nombre del archivo contiene una ruta invalida", false ),
    FILE_NOT_STORAGE_FILE( 54, "No se puede almacenar el archivo", false ),
    FILE_NOT_FOUND( 55, "El archivo no existe", false ),
    FILE_INVALID_PATH( 56, "El nombre del archivo contiene una ruta invalida", false ),
    FILE_NOT_DELETE( 57, "Error al eliminar el archivo o directorio", false ),
    PAYLOAD_UPDATE_ERROR( 58, "No existen cajeros con este PAYLOAD", false ),
    CREATE_ERROR( 59, "ocurrió un error al guardar el elemento ya existe en la base de datos ", false ),
    SAVE_ERROR( 60, "Ocurrió un error al guardar la relación de elementos es invalida ", false ),
    SAVE_ERROR_INVALID_RELATION( 61, "Ocurrió un error al guardar la relación de elementos es invalida en la base de datos ", false ),
    DELETE_ERROR_NOT_FOUND( 62, "Ocurrió un error al borrar el elemento no existe ", false ),
    DELETE_ERROR_VIOLATION( 63, "Ocurrió un error al borrar integridad de datos violada ", false ),
    DELETE_ERROR_UNKNOWN( 64, "Ocurrió un error al borrar integridad de datos desconocida ", false ),
    DELETE_ERROR( 65, "Ocurrió un error al borrar  ", false ),
    SANITIZE_ERROR_MODEL( 66, "Error de sanitización de elementos sospechosos encontrados ", false ),
    MODIFY_ERROR_INVALID_RELATION( 67, "Ocurrió un error al modificar la relación de datos invalida en la base de datos ", false ),
    MODIFY_ERROR_NOT_FOUND( 68, "Ocurrió un error al modificar no existe el elemento ", false ),
    FIND_ERROR_LIST_NOT_FOUND( 69, "No se encontraron registros", false ),
    FIND_ERROR_NOT_FOUND( 70, "Entidad no encontrada  ", false ),
    IMAGE_ERROR( 71, "Imagen no encontrada  ", false ),
    IMAGE_GROUP_ERROR( 72, "Grupo de pantallas no encontrado  ", false ),
    JOURNAL_ERROR( 73, "Journal vacío para esta consulta  ", false ),
    JOURNAL_FIID_ERROR( 74, "Journal no permitido para este fiid  ", false ),
    RECEIPT_ERROR( 75, "Ocurrió un error al generar el ticket de prueba  ", false ),
    ISO_ERROR( 76, "Error con el mensaje ISO de prueba  ", false ),
    ATM_ERROR( 77, "El cajero no existe  ", false ),
    DATE_ERROR( 78, "Fechas invalidas para consulta  ", false ),
    LICENSE_ERROR( 79, "Error al actualizar la licencia  ", false ),
    TABLE_ERROR( 80, "La tabla por consultar no existe  ", false ),
    CONNECTION_ERROR( 81, "Servicio no disponible  ", false ),
    USER_ERROR_NOT_FOUND( 82, "Usuario no encontrado  ", false ),
    USER_ERROR_ALREADY_EXISTS( 83, "El usuario ya existe  ", false ),
    UPTIME_ERROR_BY_TERMINAL_NO_RESULTS( 84, "No existen reportes de uptime para el cajero seleccionado ", false ),
    UPTIME_ERROR_DATES( 85, "Ocurrió un error con las fechas ", false ),
    UPTIME_ERROR_DATES_EMPTY( 86, "Las fechas no pueden estar vacías ", false ),
    UPTIME_ERROR_ATM_NOT_EXIST( 87, "El cajero seleccionado no existe o no cuentas con permisos para consultarlo ", false ),
    UPTIME_ERROR_IDF_NOT_EXIST( 88, "No existe la institución seleccionada ", false ),
    UPTIME_ERROR_IDF_ATM_EMPTY( 89, "La institución seleccionada no tiene cajeros en el sistema ", false ),
    UPTIME_ERROR_BUILD_EXCEL( 90, "Ocurrió un error al construir el reporte en Excel ", false ),
    USER_NOT_FOUND( 91, "El usuario no existe por favor verifique con Control de Accesos", false ),
    GROUP_NOT_REFERENCE( 92, "Se intenta crear un grupo de cajeros pero alguna de sus referencias no existe ", false ),
    GROUP_NOT_REFERENCE_2( 93, "Se intenta crear un grupo de cajeros  pero falta alguna de sus referencias ", false ),
    GROUP_UPDATE_NOT_FOUND( 94, "Se intenta actualizar un grupo de cajeros  pero no existe ", false ),
    GROUP_FIND_IDF_EMPTY_RESULT_SET( 95, "No existen FIID dadas de alta en el sistema  ", false ),
    GROUP_FIND_STATE_EMPTY_RESULT_SET( 96, "No existen estados dados de alta en el sistema  ", false ),
    GROUP_FIND_COUNTY_EMPTY_RESULT_SET( 97, "No existen municipios o ciudades que pertenezcan a ese estado  ", false ),
    GROUP_FIND_ATD_EMPTY_RESULT_SET( 98, "No existen cajeros con los criterios de búsqueda seleccionados  ", false ),
    GROUP_FIND_ATD_EMPTY_RESULT( 99, "No existe cajero con el nemotécnico especificado  ", false ),
    GROUP_FIND_GROUP_EMPTY_RESULT( 100, "No existe grupo de cajeros con el nombre especificado  ", false ),
    GROUP_FIND_GROUP_EMPTY_RESULT_SET( 101, "No existen grupos de cajeros  ", false ),
    GROUP_DUPLICATE_NAME( 102, "Se intenta crear un grupo de cajeros con un nombre que ya existe  ", false ),
    REDCAT_ERROR_DATES( 103, "ocurrió un error con las fechas ", false ),
    REDCAT_ERROR_EMPTY_DATES( 104, "Las fechas no pueden ser vacías ", false ),
    REDCAT_EMPTY_REPORT( 105, "No existen registros en las fechas indicadas ", false ),
    REDCAT_ERROR_ATM_NOT_EXISTS( 106, "El cajero seleccionado no existe o no tiene permisos pasa consultarlo ", false ),
    REDCAT_ERROR_CASSETTES( 107, "Hay un problema con las caseteras en la base de datos ", false ),
    REDCAT_ERROR_CASSETTES_CURRENCY( 108, "El tipo de moneda no es válido para el reporte redcat estándar ", false ),
    REDCAT_ERROR_CASSETTES_INDEX( 109, "El número de caseteras supera a las soportadas por el reporte estándar ", false ),
    REDCAT_ERROR_EXCEL_BUILD( 110, "Error al construir el reporte de Excel ", false ),
    REDCAT_ERROR_FTP_CONNECTION_LOGIN( 111, "Error al autenticarse con el servidor de archivos redcat ", false ),
    REDCAT_ERROR_FTP_CONNECTION_SERVER( 112, "No se pudo establecer conexión con el servidor de archivos ", false ),
    REDCAT_ERROR_PARAMS( 113, "Se debe indicar cajero o FIID para la búsqueda ", false ),
    REDCAT_ERROR_EMTPY_FIID( 114, "No hay registros de corte para esta institución ", false ),
    REDCAT_ERROR_DAT_REPORT( 115, "Hubo un problema al construir el reporte ", false ),
    REDCAT_ERROR_FILE_ALREADY_EXISTS( 116, "Ya existe un archivo con este nombre en el servidor FTP ", false ),
    REDCAT_ERROR_INVALID_FORCECUT_DATE( 117, "Hay un problema con la fecha de corte asignada a la institución  ", false ),
    REDCAT_ERROR_FORCECUT_ARLEADY_DONE( 118, "El corte forzado de este día ya se realizó para esta institución  ", false ),
    REDCAT_ERROR_IDF_NOT_FOUND( 119, "La institución no existe ", false ),
    REDCAT_ERROR_AUTOMATIC_TASK_FAILED( 120, "Fallo al realizar el corte forzado programado para la institución  ", false ),
    ALGORITHM_NOT_REFERENCE( 121, "Se intenta crear o actualizar un algoritmo de dispensado, pero alguna de sus referencias no existe ", false ),
    ALGORITHM_NOT_REFERENCE_2( 122, "Se intenta crear o actualizar un algoritmo de dispensado, pero alguna de sus referencias no existe ", false ),
    ALGORITHM_DUPLICATE_NAME( 123, "Se intenta crear un algoritmo de dispensado con un nombre que ya existe  ", false ),
    ALGORITHM_UPDATE_NOT_FOUND( 124, "Se intenta actualizar un algoritmo de dispensado, pero no existe  ", false ),
    ALGORITHM_FIND_GROUP_EMPTY_RESULT( 125, "No existe algoritmo de dispensado con el nombre especificado  ", false ),
    ALGORITHM_FIND_GROUP_EMPTY_RESULT_SET( 126, "No existen algoritmos de dispensado  ", false ),
    USER_ALREADY_EXIST( 127, "El usuario ya existe", false ),
    LDAP_ERROR_USER_NOT_MEMBER( 128, "El usuario no es miembro de la rama en LDAP", false ),
    LDAP_ERROR_USER_NOT_FOUND_DATA( 129, "El usuario no existe en la base de datos", false ),
    LDAP_ERROR_COMMUNICATION( 130, "Problema de comunicación con LDAP", true ),
    LDAP_ERROR_USER_NOT_FOUND_LDAP( 131, "El usuario no existe en LDAP", false ),
    LDAP_ERROR_USER_TO_MANY( 132, "Muchos usuarios asociados con ese ID", false ),
    LDAP_ERROR_USER_INVALID_CREDENTIALS( 133, "Credenciales invalidas", false ),
    LDAP_ERROR_QUERY( 134, "No hay resultados en LDAP", false ),
    USER_ALREADY_EXIST_NOT_DELETE( 135, "El usuario aun existe en LDAP. Favor eliminarlo en LDAP primero", false ),
    ROLES_LIST_EMPTY( 136, "Lista de roles vacía", false ),
    USER_LIST_EMPTY( 137, "Lista de usuarios vacía", false ),
    PRIVILEGE_LIST_EMPTY( 138, "Lista de privilegios vacía", false ),
    MENU_INTEGRITY( 139, "El menu tiene una restricción de integridad con algún Rol", false ),
    MENU_LIST_EMPTY( 140, "Lista de menús vacía", false ),
    ROLE_NOT_FOUND( 141, "No existe el rol que se quiere actualizar", false ),
    ROLE_NOT_FOUND_2( 142, "No existe el rol que se requiere eliminar", false ),
    MENU_ROLE_LIST_EMPTY( 143, "Lista de roles y menús vacía", false ),
    ROLE_INTEGRITY( 144, "El Rol tiene una restricción de integridad con algún usuario. Verifique el Rol no exista en LDAP y actualice los usuarios que tenían ese Rol", false ),
    PRIVILEGE_NOT_FOUND( 145, "No existe el privilegio", false ),
    PRIVILEGE_INTEGRITY( 146, "El privilegio tiene una restricción de integridad con algún rol", false ),
    JKE_ISO_NO_APP( 147, "La aplicación seleccionada es invalida", false ),
    DATABASE_CREATE_ALREADY_EXIST( 148, "Ya existe una entidad en la base de datos con el ID ingresado", false ),
    DATABASE_CREATE_NO_REFERENCE( 149, "Se intenta crear una entidad pero alguna de sus referencias no existe", false ),
    DATABASE_CREATE_NO_REFERENCE_2( 150, "Se intenta crear una entidad pero falta alguna de sus referencias", false ),
    DATABASE_CREATE_UNIQUE_DUPLICATE( 151, "Se intenta crear entidad pero tiene restricciones únicas que ya existen", false ),
    DATABASE_MODIFY_NO_EXIST( 152, "No existe la entidad que se quiere modificar", false ),
    DATABASE_MODIFY_NO_REFERENCE( 153, "Se intenta modificar una entidad pero alguna de sus referencias no existe", false ),
    DATABASE_MODIFY_NO_REFERENCE_2( 154, "Se intenta modificar una entidad pero falta alguna de sus referencias", false ),
    DATABASE_DELETE_NO_EXIST( 155, "No existe la entidad que se quiere eliminar", false ),
    DATABASE_DELETE_NO_REFERENCE( 156, "Se intenta eliminar una entidad pero alguna de sus referencias no existe", false ),
    DATABASE_DELETE_NO_REFERENCE_2( 157, "Se intenta eliminar una entidad pero falta alguna de sus referencias", false ),
    DATABASE_FIND_NO_EXIST( 158, "La entidad buscada no existe", false ),
    IDF_NOT_FOUND( 159, "No existe la institución buscada", false ),
    IDF_NOT_ALLOW( 160, "No cuentas con permisos para ver todas las instituciones", false ),
    LOG_NOT_FOUND( 161, "No existen resultado de búsqueda con los criterios seleccionados", false ),
    JOURNAL_NOT_ALLOW( 162, "No tiene permisos para ver estos registros", false ),
    DATABASE_FIND_LIST_EMPTY( 163, "No existen resultado de busqueda", false ),
    XFS_NOT_FOUND( 164, "Se recibe un mensaje XFS con un código que no existe", false ),
    ATM_NO_EXCHANGE_KEY( 165, "No se pudo realizar el intrecambio de llaves 3DES", false ),
    ATM_NO_IMAGE( 166, "La imagen solicitada no existe", false ),
    ATM_INVALID_TRACK_2( 167, "TRACK 2 Invalido", false ),
    BANC_BIN( 168, "No se encuentra un prefijo para la tarjeta ingresada en el cajero", false ),
    INVALID_AMOUNT_DISP( 169, "El monto seleccionado no se puede dispensar", false ),
    UMBRALES_ERROR( 170, "La denominación configurada no es apta para el algoritmo de umbrales", false ),
    DENOMINATION_INVALID( 171, "Denominación invalida", false ),
    LIMIT_NOTES( 172, "El numero de notas excede el limite permitido de 50", false ),
    BUTTON_SECTION( 173, "Sección de pantallas no encontrada", false ),
    RECEIPT_HEADER( 174, "Header Invalido para este recibo", false ),
    RECEIPT_LABEL( 175, "La etiqueta configurada es invalida", false ),
    RECEIPT_BODY( 176, "Datos invalidos  no se puede armar el recibo", false ),
    RESPONSE_TIMEOUT( 177, "No se recibio respuesta para la transacción", false ),
    REVERSAL_TYPE_MESSAGE( 178, "Tipo de mensaje Invalido para un reverso", false ),
    REVERSAL_TRAN_CODE( 179, "Solo se permite reversos de transacciones financieras", false ),
    REVERSAL_AP( 180, "Solo transacciones apobadas pueden ser reversadas", false ),
    SURCHARGE_NOT_FOUND( 181, "No existe comisión para esta transacción", false ),
    INVALID_TRAN_CODE( 182, "Código de transacción invalida", false ),
    ONLY_ON_US( 183, "TRANSACCIÓN NO PERMITIDA POR SU BANCO", false ),
    APC_NOT_FOUND( 184, "No existe un perfil APC para esta FIID y transacción", false ),
    RECEIPT_ERROR_1( 185, "No existe un ticket para la transacción", false ),
    FILE_NO_READ( 186, "No se puede convertir el archivo", false ),
    INVALID_OPERATION( 187, "La operación es invalida", false ),
    INVALID_MODULE( 188, "El modulo para la operación batch es invalido", false ),
    JWT_NO_PRIVILEGE( 189, "No cuenta con los permisos necesarios para utilizar este modulo", false ),
    JWT_EXPIRED( 190, "El Token usado para esta petición esta expirado", false ),
    JWT_MALFORMED( 191, "El Token usado para esta petición esta corrupto", false ),
    SERVER_ERROR( 192, "Ocurrió un error severo en el API, favor de reportarlo con soporte", true ),
    LOGIN_ERROR( 193, "Empty Template", false ),
    SCREEN_FIND_GROUP_EMPTY_RESULT( 194, "No existe grupo de pantallas con el nombre especificado  ", false ),

    RCPT_NOT_REFERENCE( 195, "Se intenta crear o actualizar un rcpt, pero alguna de sus referencias no existe ", false ),
    RCPT_NOT_REFERENCE_2( 196, "Se intenta crear o actualizar un rcpt, pero alguna de sus referencias no existe ", false ),
    RCPT_DUPLICATE_NAME( 197, "Se intenta crear un rcpt con un nombre que ya existe  ", false ),
    RCPT_UPDATE_NOT_FOUND( 198, "Se intenta actualizar un rcpt, pero no existe  ", false ),
    RCPT_FIND_GROUP_EMPTY_RESULT( 199, "No existe rcpt con el nombre especificado  ", false ),
    RCPT_FIND_GROUP_EMPTY_RESULT_SET( 200, "No existen script para recibos", false ),
    IMAGE_FIND_GROUP_EMPTY_RESULT_SET( 201, "No existen imagenes que mostrar", false ),
    SCREEN_FIND_GROUP_EMPTY_RESULT_SET( 202, "No existen payloads que mostrar", false ),

    APC_NOT_REFERENCE( 203, "Se intenta crear o actualizar un apc, pero alguna de sus referencias no existe ", false ),
    APC_NOT_REFERENCE_2( 204, "Se intenta crear o actualizar un apc, pero alguna de sus referencias no existe ", false ),
    APC_DUPLICATE_NAME( 205, "Se intenta crear un apc con un nombre que ya existe  ", false ),
    APC_UPDATE_NOT_FOUND( 206, "Se intenta actualizar un apc, pero no existe  ", false ),
    APC_FIND_GROUP_EMPTY_RESULT( 207, "No existe apc con el nombre especificado  ", false ),
    APC_FIND_GROUP_EMPTY_RESULT_SET( 208, "No existen apc", false ),

    BIN_NOT_REFERENCE( 209, "Se intenta crear o actualizar un bin, pero alguna de sus referencias no existe ", false ),
    BIN_NOT_REFERENCE_2( 210, "Se intenta crear o actualizar un bin, pero alguna de sus referencias no existe ", false ),
    BIN_DUPLICATE_NAME( 211, "Se intenta crear un bin con un nombre que ya existe  ", false ),
    BIN_UPDATE_NOT_FOUND( 212, "Se intenta actualizar un bin, pero no existe  ", false ),
    BIN_FIND_GROUP_EMPTY_RESULT( 213, "No existe bin con el nombre especificado  ", false ),
    BIN_FIND_GROUP_EMPTY_RESULT_SET( 214, "No existen bines", false ),

    SYSTEM_ERROR_SERVICE( 999, "Ocurrió un error interno", true ),
    APPROVED( 1000, "APROBADO ", false ),
    REFER_TO_CARD_ISSUER( 1001, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    REFER_TO_SPECIAL( 1002, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    INVALID_MERCHANT( 1003, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    PICK_UP( 1004, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    DO_NOT_HONOR( 1005, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    ERROR( 1006, "ERROR ", false ),
    PICK_UP_CARD( 1007, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    HONOR_WITH( 1008, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    REQUEST_IN_PROGRESS( 1009, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    APPROVED_FOR_PARTIAL( 1010, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    APPROVED_VIP( 1011, "APROBADO ", false ),
    INVALID_TRANSACTION_ISO( 1012, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    INVALID_AMOUNT( 1013, "MONTO INVALIDO ", false ),
    INVALID_CARD_NUMBER( 1014, "EL NÚMERO DE TARJETA NO ES VÁLIDO ", false ),
    NO_SUCH_ISSUER( 1015, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    APPROVED_UPDATE( 1016, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    CUSTOMER_CANCELLATION( 1017, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    CUSTOMER_DISPUTE( 1018, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    RE_ENTER_TRANSACTION( 1019, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    INVALID_RESPONSE( 1020, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    NO_ACTION_TAKEN( 1021, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    SUSPECTED_MALFUNCTION( 1022, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    UNACCEPTABLE( 1023, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    FORMAT_ERROR( 1030, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    BANK_NOT_SUPPORTED_BY( 1031, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    COMPLETED_PARTIALLY( 1032, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    EXPIRED_CARD( 1033, "LA TARJETA INTRODUCIDA HA EXPIRADO ", false ),
    SUSPECTED_FRAUD( 1034, GeneralError.ISSUER_REJECT_REPORT, false ),
    CARD_ACCEPTOR_CONTACT( 1035, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    RESTRICTED_CARD( 1036, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    CARD_ACCEPTOR_CALL( 1037, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    ALLOWABLE_PIN_TRIES( 1038, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    NO_CREDIT_ACCOUNT( 1039, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    REQUESTED_FUNCTION( 1040, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    LOST_CARD( 1041, GeneralError.ISSUER_REJECT_REPORT, false ),
    NO_UNIVERSAL_ACCOUNT( 1042, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    STOLEN_CARD_PICK_UP( 1043, GeneralError.ISSUER_REJECT_REPORT, false ),
    NO_INVESTMENT( 1044, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    NOT_SUFFICIENT_FUNDS( 1051, "FONDOS NO SUFICIENTES ", false ),
    NO_CHEQUING_ACCOUNT( 1052, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    NO_SAVINGS_ACCOUNT( 1053, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    EXPIRED_CARD_1( 1054, "LA TARJETA INTRODUCIDA HA EXPIRADO ", false ),
    INCORRECT_PIN( 1055, "NIP INVALIDO ", false ),
    NO_CARD_RECORD( 1056, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    TRANSACTION_NOT_CARD( 1057, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    TRANSACTION_NOT_TERMINAL( 1058, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    SUSPECTED_FRAUD_1( 1059, GeneralError.ISSUER_REJECT_REPORT, false ),
    CARD_ACCEPTOR_CONTACT_A( 1060, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    EXCEEDS_WITHDRAWAL( 1061, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    RESTRICTED_CARD_A( 1062, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    SECURITY_VIOLATION( 1063, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    EXCEEDS_WITHDRAWAL_FL( 1065, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    CARD_ACCEPTOR_CALL_SEC( 1066, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    HARD_CAPTURE( 1067, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    PIN_TRIES_EXCEEDED( 1075, "INTENTOS DE NIP EXCEDIDOS ", false ),
    RESERVED_FOR_PRIVATE_76( 1076, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    RESERVED_FOR_PRIVATE_77( 1077, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    RESERVED_FOR_PRIVATE_78( 1078, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    RESERVED_FOR_PRIVATE_79( 1079, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    RESERVED_FOR_PRIVATE_80( 1080, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    RESERVED_FOR_PRIVATE_81( 1081, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    RESERVED_FOR_PRIVATE_86( 1086, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    RESERVED_FOR_PRIVATE_87( 1087, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    RESERVED_FOR_PRIVATE_88( 1088, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    RESERVED_FOR_PRIVATE_89( 1089, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    CUTOFF_IS_IN_PROCESS_90( 1090, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    ISSUER_INOPERATIVE( 1091, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    NOT_ROUTING( 1092, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    VIOLATION_OF_LAW( 1093, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    DUPLICATE_TRANSMISSION( 1094, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    RECONCILE_ERROR( 1095, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    SYSTEM_MALFUNCTION( 1096, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    ARQC_FAILURE_DECLINE( 1097, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    SECURITY_MODULE_INV_PARAM( 1098, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    SECURITY_MODULE_FAILURE( 1099, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    KEY1_RECORD_NOT( 1100, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    ATC_CHECK_FALURE( 1101, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    CVR_DECLINE( 1102, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    TVR_DECLINE( 1103, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    FALLBACK_DECLINE( 1104, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    ARQC_FAILURE_CAPTURE( 1105, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    CVR_CAPTURE( 1106, GeneralError.NOT_PROCESS_TRANSACTION, false ),
    UN_SUPPORT( 1107, "ERROR NO DEFINIDO", false ),
    
    ;


    private final int code;

    private final String message;

    private final boolean critical;

    CatalogError( int code, String message, boolean critical ) {
        this.code = code;
        this.message = message;
        this.critical = critical;
    }

    @Override
    public int getCode() {
        return code;
    }

    @Override
    public String getMessage() {
        return message;
    }

    @Override
    public boolean isCritical() {
        return critical;
    }

    @Override
    public ErrorCode findByCodeAndCritical( int code ) {
        for ( ErrorCode errorCode : CatalogError.values() ) {
            if ( errorCode.getCode() == code && errorCode.isCritical() ) {
                return errorCode;
            }
        }
        return NO_ERROR;
    }

    @Override
    public ErrorCode findByCode( int code ) {
        for ( ErrorCode errorCode : CatalogError.values() ) {
            if ( errorCode.getCode() == code ) {
                return errorCode;
            }
        }
        return NO_ERROR;
    }
    
    private static class GeneralError{
        
        private static final String NOT_PROCESS_TRANSACTION = "POR EL MOMENTO NO SE PUEDE PROCESAR LA TRANSACCIÓN";
        private static final String ISSUER_REJECT_REPORT = "LA TRANSACCIÓN SE RECHAZÓ POR UN REPORTE EN LA TARJETA";
    }
}
